#!/usr/bin/env php

<?php

$ROOT_DIR = '/Users/acarlino/Sites/lessons-new';
chdir($ROOT_DIR);

foreach(range(2, 21) as $num) {
	foreach(['begin', 'end'] as $marker) {
		$lessonNum = str_pad($num, 2, '0', STR_PAD_LEFT);
		$branchName = sprintf(
			'lesson-%s-%s',
			$lessonNum,
			$marker
		);
		$dirName = ucfirst($branchName);
		$lessonDir = $ROOT_DIR . '/' .$dirName;

		exec("cd $lessonDir && rm install.php");
	}
}